// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package query

import (
	"time"
)

type ReadingHistory struct {
	ID          int32
	VolumeID    int32
	CurrentPage int32
	CreatedAt   time.Time
	UserID      int32
	PagesRead   int32
}

type Series struct {
	ID        int32
	Name      string
	Notes     string
	CreatedAt time.Time
	UserID    int32
}

type User struct {
	ID             int32
	ProviderID     string
	FirebaseUserID string
	Email          string
	DisplayName    string
	CreatedAt      time.Time
}

type Volume struct {
	ID          int32
	SeriesID    int32
	Name        string
	Notes       string
	CurrentPage int32
	CreatedAt   time.Time
	UserID      int32
	Status      string
}
